### ISSUE TITLE
Update ShellCheck version

### ISSUE THREAD

**Issue by pbrisbin** [mcfilib/codeclimate-shellcheck#64]
I'd like to make a PR updating ShellCheck to latest (0.7.0) because I'm seeing Issues on Code Climate that are incorrect due to bugs in the 0.4.6 version. I can provide details if interested, but I know the bug is fixed in my local 0.6.0 binary, so I assume updating will resolve it.

Looking at this repo, it seems the version of ShellCheck is not pinned anywhere, and so just performing an un-cached build should update things to latest. Is that correct?

If so, how do we poke Code Climate to rebuild the image? Is an implicit version desired or should we look to pin it in (I assume) the cabal file?

**Comment by mcfilib** [comment]
i’m currently on vacation and haven’t worked on the image in more than, so you might be best pressing ahead with this yourself.

see too unresolved issues in currently open pull request, which i suspect will also be an issue.

as far as getting code climate to bump the image on their infrastructure, i’m not sure how that works now. before i asked in their slack channel or someone who worked there would want some changes on a pull request here.

so perhaps one way forward is for you to pin the version, resolve that outstanding issue, open a pull request and i’ll try and contact them.

**Comment by pbrisbin** [comment]
> perhaps one way forward is for you to pin the version, resolve that outstanding issue, open a pull request and i’ll try and contact them.

:+1:

**Comment by pbrisbin** [comment]
https://github.com/mcfilib/codeclimate-shellcheck/pull/65
