### ISSUE TITLE
transfer ownership

### ISSUE THREAD

**Issue by mcfilib** [mcfilib/codeclimate-shellcheck#66]
i do not currently have time to maintain this project and i'm not currently using `codeclimate-shellcheck`, so would like to find a new maintainer.

i'll be archiving and then deleting the repo in approx. 3 months if no one is interested in taking it on.

**Comment by mcfilib** [comment]
@pbrisbin @mrb @acook @wfleming you've all contributed to the project over the last few years. is this something you'd be interested in?

**Comment by acook** [comment]
I'm not much of a Haskeller but I can host it on my account if need be. Really, it would make more sense if @CodeClimate hosted it themselves.

**Comment by pbrisbin** [comment]
I can take it if the only alternative is archiving. I agree having Code Climate involved would be ideal. I'd be happy to help out with a transition to @codeclimate-community, if that's an option.

**Comment by philipcunningham** [comment]
@acook @pbrisbin thanks both for chiming in.

agree that transitioning to @codeclimate-community would be desirable but don't really have any contacts to help make that happen. @pbrisbin that something you could help with?

**Comment by efueger** [comment]
@mcfilib - sure! I can get that started from Code Climate's side. 👌

**Comment by philipcunningham** [comment]
@efueger perfect! thanks!

**Comment by philipcunningham** [comment]
@efueger i can transfer this to an individual within the @codeclimate-community organisation and then they can transfer it to the organisation itself. who's the best person to transfer to?

**Comment by wfleming** [comment]
@mcfilib I'm one of the owners on that org, so if you transfer it to me I can transfer it to the org.

**Comment by philipcunningham** [comment]
@wfleming can you delete your fork? i get:

> wfleming/codeclimate-shellcheck already exists

**Comment by efueger** [comment]
Hi @mcfilib - one of my dev colleagues forked your repo to our [codeclimate-community](https://github.com/codeclimate-community/codeclimate-shellcheck) org.
- (we made some updates Friday, but ran into some trouble and had to roll it back.)
- I don't think we'll run into any ownership issues 👌

Just waiting on confirmation from my team before asking you to archive this one.

**Comment by wfleming** [comment]
Oops. Done, @mcfilib.

~ will

**Comment by wfleming** [comment]
@efueger I think it's worth carrying through with the ownership change so that if people are looking for the repo and find this one via a search engine they'll get redirected automatically to the "right" copy.

**Comment by philipcunningham** [comment]
@wfleming agreed! that's the transfer requested. not sure how that's handled in the github ui but hopefully you should get something soon.
